version: "3.7"

services:
  shinkan:
    image: conveni-api
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
    container_name: conveni-api
